INSERT INTO GRUPO (nombre) VALUES ('1MA');
INSERT INTO GRUPO (nombre) VALUES ('1MB');
INSERT INTO GRUPO (nombre) VALUES ('1MC');
INSERT INTO GRUPO (nombre) VALUES ('1MD');

INSERT INTO GRUPO (nombre) VALUES ('2MA');
INSERT INTO GRUPO (nombre) VALUES ('2MB');
INSERT INTO GRUPO (nombre) VALUES ('2MC');
INSERT INTO GRUPO (nombre) VALUES ('2MD');

INSERT INTO GRUPO (nombre) VALUES ('3MA');
INSERT INTO GRUPO (nombre) VALUES ('3MB');
INSERT INTO GRUPO (nombre) VALUES ('3MC');
INSERT INTO GRUPO (nombre) VALUES ('3MD');